#Serverless build instructions - defines functions and parameters.
service: pma-api-projects

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2
  apiName: pma-mono-api


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"

resources:
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: prod-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
         Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: prod-ApiGatewayRestApiRootResourceId



functions:

#Project functions:

  create:
    handler: create.main
    events:
      - http:
          path: projects
          method: post
          cors: true
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: projects/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: projects/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  get:
    handler: get.main
    events:
      - http:
          path: projects/{id}
          method: get
          cors: true
          authorizer: aws_iam
