#Serverless build instructions - defines functions and parameters.
service: pma-api-users

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2
  apiGateway:
    restApiId:
      'Fn::ImportValue': prod-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': prod-ApiGatewayRestApiRootResourceId

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"


functions:

#User functions:

  get:
    handler: get.main
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
          authorizer: aws_iam

  all:
    handler: all.main
    events:
      - http:
          path: users/all
          method: get
          cors: true
          authorizer: aws_iam

  list:
    handler: list.main
    events:
      - http:
          path: users/list
          method: get
          cors: true
          authorizer: aws_iam

  create:
    handler: create.main
    events:
      - http:
          path: users
          method: post
          cors: true
          authorizer: aws_iam

  search:
    handler: search.main
    events:
      - http:
          path: users/search/{search}
          method: get
          cors: true
          authorizer: aws_iam
