# NOTE: update this with your service name
service: pma-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"

functions:

  create:
    handler: create.main
    events:
      - http:
          path: projects
          method: post
          cors: true
          authorizer: aws_iam


  get-user:
    handler: get-user.main
    events:
      - http:
          path: projects/{id}
          method: get
          cors: true
          authorizer: aws_iam


  list-team:
    handler: list-team.main
    events:
      - http:
          path: projects
          method: get
          cors: true
          authorizer: aws_iam

  list-users:
    handler: list-users.main
    events:
      - http:
          path: projects
          method: get
          cors: true
          authorizer: aws_iam


  update:
    handler: update.main
    events:
      - http:
          path: projects/{id}
          method: put
          cors: true
          authorizer: aws_iam


  delete:
    handler: delete.main
    events:
      - http:
          path: projects/{id}
          method: delete
          cors: true
          authorizer: aws_iam
